[package]
name = "microfetch"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
nix = {version = "0.29", features = ["fs"]}
color-eyre = { version = "0.6", default-features = false }



